import { useSelector } from 'react-redux';
import { useState } from 'react';
import axios from 'axios';
import type { RootState } from '../Redux/store';
import coinService from '../Services/CoinService';
import './Recommendations.css';

function Recommendations() {
  const selectedSymbols = useSelector((state: RootState) => state.coins.selectedCoinIds);
  const [advice, setAdvice] = useState<any>({});
  const [loading, setLoading] = useState<any>({});
  
  const [freeQuery, setFreeQuery] = useState("");
  const [queryResponse, setQueryResponse] = useState("");
  const [queryLoading, setQueryLoading] = useState(false);

  const apiKey = import.meta.env.VITE_OPENAI_API_KEY; // Ensure this is set in your .env file

  const getAIAdvice = async (symbol: string) => {
    setLoading((prev: any) => ({ ...prev, [symbol]: true }));
    const idMap: any = { 'BTC': 'bitcoin', 'ETH': 'ethereum', 'DOGE': 'dogecoin', 'USDT': 'tether', 'BNB': 'binancecoin', 'SOL': 'solana', 'XRP': 'ripple' };
    const coinId = idMap[symbol.toUpperCase()] || symbol.toLowerCase();

    try {
      const stats = await coinService.getAIStats(coinId);
      const prompt = `Act as a crypto expert. Analyze ${stats.name}: Price: $${stats.current_price}, 30d change: ${stats.change_30d}%, 200d change: ${stats.change_200d}%. Should I BUY/SELL/HOLD? Answer in 2 short sentences.`;
      const response = await axios.post('https://api.openai.com/v1/chat/completions',
        { model: "gpt-3.5-turbo", messages: [{ role: "user", content: prompt }], max_tokens: 150 },
        { headers: { 'Authorization': `Bearer ${apiKey}` } }
      );
      setAdvice((prev: any) => ({ ...prev, [symbol]: response.data.choices[0].message.content }));
    } catch (err) { setAdvice((prev: any) => ({ ...prev, [symbol]: "ERROR: Connection timeout." })); }
    setLoading((prev: any) => ({ ...prev, [symbol]: false }));
  };

  const handleFreeQuery = async () => {
    if (!freeQuery) return;
    setQueryLoading(true);
    try {
      const response = await axios.post('https://api.openai.com/v1/chat/completions',
        { model: "gpt-3.5-turbo", messages: [{ role: "user", content: freeQuery }] },
        { headers: { 'Authorization': `Bearer ${apiKey}` } }
      );
      setQueryResponse(response.data.choices[0].message.content);
    } catch (err) { setQueryResponse("SIGNAL LOST..."); }
    setQueryLoading(false);
  };

  // PRO REPORT FUNCTION FOR AUTO TIPS
  const downloadFullReport = async (symbol: string, aiAdvice: string) => {
    const idMap: any = { 'BTC': 'bitcoin', 'ETH': 'ethereum', 'DOGE': 'dogecoin', 'USDT': 'tether', 'BNB': 'binancecoin', 'SOL': 'solana', 'XRP': 'ripple' };
    const coinId = idMap[symbol.toUpperCase()] || symbol.toLowerCase();
    try {
        const data = await coinService.getFullReportData(coinId);
        const now = new Date();
        const reportContent = `
==================================================
        CRYPTONITE TERMINAL // NEURAL_REPORT
==================================================
TIMESTAMP: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
STATUS: AUTHORIZED ANALYSIS
--------------------------------------------------
ASSET: ${data.name} (${symbol.toUpperCase()})
MARKET_METRICS:
> Price (USD): $${data.current_price.toLocaleString()}
> Price (EUR): €${data.eur.toLocaleString()}
> Price (ILS): ₪${data.ils.toLocaleString()}
> Market Cap: $${data.market_cap.toLocaleString()}
> 30-Day Change: ${data.change_30d.toFixed(2)}%
> 200-Day Change: ${data.change_200d.toFixed(2)}%
--------------------------------------------------
NEURAL_ADVISORY_OUTPUT:
"${aiAdvice}"
--------------------------------------------------
!!! IMPORTANT_DISCLAIMER !!!
This report is generated by an AI engine. 
Cryptonite Terminal does not provide financial advice. 
Cryptocurrency trading involves high risk. 
Make your own decisions and trade responsibly.
--------------------------------------------------
© 2026 CRYPTONITE // SECURE_DECENTRALIZED_SYSTEM
==================================================`;
        const element = document.createElement("a");
        element.href = URL.createObjectURL(new Blob([reportContent], {type: 'text/plain'}));
        element.download = `Report_${symbol}.txt`;
        element.click();
    } catch (e) { alert("Report failed."); }
  };

  // DOWNLOAD FUNCTION FOR FREE REQUEST
  const downloadCustomQueryReport = (query: string, responseText: string) => {
    const now = new Date();
    const reportContent = `
==================================================
      CRYPTONITE TERMINAL // CUSTOM_INQUIRY
==================================================
TIMESTAMP: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}
STATUS: DECRYPTED_DIRECT_LINK
--------------------------------------------------
USER_PROMPT:
"${query}"

NEURAL_LINK_RESPONSE:
"${responseText}"

--------------------------------------------------
!!! IMPORTANT_DISCLAIMER !!!
This analysis is generated by an Artificial Intelligence. 
Cryptonite Terminal does not provide financial advice. 
The user bears full responsibility for all trading 
decisions based on this information.
--------------------------------------------------
© 2026 CRYPTONITE // SECURE_DECENTRALIZED_SYSTEM
==================================================`;

    const element = document.createElement("a");
    element.href = URL.createObjectURL(new Blob([reportContent], {type: 'text/plain'}));
    element.download = `AI_Inquiry_${now.getTime()}.txt`;
    element.click();
  };

  return (
    <div className="page-container">
      <div className="title-wrapper">
        <h1 className="section-title">Neural_Advisory_Node</h1>
      </div>
      <p className="system-status-text">
  NEURAL_LINK: <span style={{ color: '#00f2ff' }}>ESTABLISHED</span> // 
  GPT_ENGINE: <span style={{ color: '#00ff00' }}>ONLINE</span> // 
  AWAITING_QUERY_DECRYPTION...
</p><br></br>

      <div className="cyber-grid">
        {selectedSymbols.length === 0 ? (
          <div className="no-selection-msg">OFFLINE: NO_NODES_ACTIVE</div>
        ) : (
          selectedSymbols.map(symbol => (
            <div key={symbol} className="ai-card">
              <div className="robot-head">
                🤖
                {loading[symbol] && <div className="loading-dots"><div className="dot"></div><div className="dot"></div><div className="dot"></div></div>}
              </div>
              <h2 className="coin-name">{symbol}</h2>
              <button className="ai-button" onClick={() => getAIAdvice(symbol)} disabled={loading[symbol]}>
                {loading[symbol] ? "SCANNING..." : "EXECUTE_ANALYSIS"}
              </button>
              {advice[symbol] && (
                <div className="ai-response-box">
                    <p>{advice[symbol]}</p>
                    <button className="save-btn" onClick={() => downloadFullReport(symbol, advice[symbol])}>💾 Download Pro Report</button>
                </div>
              )}
            </div>
          ))
        )}
      </div>

      <div className="cyber-divider" style={{ marginTop: '80px' }}></div>

      <div className="free-query-section">
        <div className="title-wrapper" style={{ position: 'relative', zIndex: 10, marginBottom: '40px' }}>
            <h2 className="section-title" style={{ fontSize: '1.2rem' }}>Direct_Neural_Link</h2>
        </div>
        
        <div className="terminal-box">
            <div className="terminal-header">
                <span><span style={{ color: '#555' }}>SYS_INPUT:</span> V.2.0.4</span>
                <span><span style={{ color: '#555' }}>STATUS:</span> <span style={{ color: '#00ff00' }}>READY</span></span>
            </div>
            <textarea 
                className="terminal-input"
                placeholder="PROMPT_INPUT >> Ask any crypto question..."
                value={freeQuery}
                onChange={(e) => setFreeQuery(e.target.value)}
            />
            <button className="terminal-button" onClick={handleFreeQuery} disabled={queryLoading}>
                {queryLoading ? "LINKING..." : "QUERY_NODE"}
            </button>
            
            {queryResponse && (
                <div className="ai-response-box" style={{ marginTop: '70px' }}>
                    <span className="box-label">INCOMING_MESSAGE:</span>
                    <p>{queryResponse}</p>
                    {/* DOWNLOAD BUTTON FOR FREE REPLY */}
                    <button className="save-btn" onClick={() => downloadCustomQueryReport(freeQuery, queryResponse)}>
                        💾 Download Inquiry Report
                    </button>
                </div>
            )}
        </div>
      </div>
    </div>
  );
}

export default Recommendations;